= Introduction <cap:intro>

== Overview <sec:iot_overview>
From the first computational machines introduced in the mid-20th century to the present day, the evolution of computer science has been characterized by continuous innovation and rapid technological advancement. The advent of the Internet toward the end of the century profoundly transformed our interaction with technology, reshaping social interactions, economic forces, political dynamics, and the way we access and share information.\
In recent decades, one of the most significant developments in this field has been the emergence of the Internet of Things (IoT) paradigm. This concept envisions a world where everyday objects, ranging from healthcare sensors and industrial actuators to home appliances, are interconnected enabling them to collect and exchange data. 
This connectivity facilitates a wide array of applications that enhance daily life through automation, remote sensing and control. Since its introduction, IoT has experienced an exponential growth and widespread adoption across various sectors, from smart homes to industrial automation, healthcare, agriculture, disaster recovery and many others.\ 

The history of IoT started way back in 1982 when a vending machine was connected to the internet and set to display the number of bottles with its temperature. A decade later, in 1991, Mark Weiser introduced the concept of ubiquitous computing @ubiquitosus_computing, which was just a theoretical expression of what IoT is today. The first accepted technology used in this field was the Radio Frequency Identification (RFID) in 1998, a wireless technology using radio waves to automatically identify and track tags attached to objects. Exactly from here, Kevin Ashton, at the time executive director of the Auto-ID center at the MIT, in 1999 @ashton2009internet during a speech about the new idea of using RFID in the P&G's supply chain, coined the term "Internet of Things".
The Auto-ID center was a collaboration between industries and private sectors, holding 60 researchers and 15 professional leading research networks in IoT. The first conference on IoT was organized and held in 2008, and from there many countries embraced it and drafted action plans on the IoT. Later, in 2014, Auto-ID lab released a state-of-the-art report on IoT @auto-id-lab.\
At the beginning, there has still been skepticism about embracing IoT until when tech giants that made IoT big business opportunities. Various report projected that 25 billion devices were connected before 2020 @fehske2011global, increasing to 38 billion by the end of 2025 and 50 billion by the end of 2030 @chui2021internet. According to a market research estimate, the global IoT industry was worth 245 billion dollars in 2020 and is predicted to grow to 8,131 billions by 2030 @al2020internet.\ 

Nowadays, IoT environments are characterized by the presence of a large number of heterogeneous and resource constrained devices, in terms of memory, CPU, bandwidth or battery and often are massively deployed in areas of interest to enable IoT applications.  
However, they may be used in contexts where the communication is over error-prone and lossy radio channels. Due to their inherent and limited characteristics, IoT devices may experience various network performance problems, expecially when deployed in hostile environments (e.g. war zones, agricultural fields, disasterd zones ecc.), or suffer from excessive energy consumption resulting from network congestions. \
These challenges have driven the development and standardization of a wide range of different protocols and frameworks for management for constrained devices and networks. 
This includes a stack of communication solutions designed to optimize resources at various levels. From wireless communication technologies like Zigbee @zigbee, BLE @ble, LoraWAN, Sigfox and NB-IoT @lpwan_overview for Low-Power Wide-Area Networks (LPWAN), to network-layer solutions such as 6LowPAN @6lowpan and RPL @rpl that enable efficient IPv6 routing over lossy channels. At the application level, we can find lightweight messaging protocols like MQTT and CoAP @mqtt_coap , which have become essential for reliable data exchange in resource-constrained environments. Furthermore, there are also specialized management interfaces such as LWM2M or XMPP @l2m2m_xmpp, introduced to manage the remote configuration and monitoring of these devices.\ 

This massive expansion of the IoT ecosystem has been further accelerated by the development with other innovative technologies. In particular, the introduction of the 5G cellular network technology @5G_iot_survey fulfill the needs of complex IoT architectures providing the high data rate and low latency required for real-time data transmission. Moreover, the new promising 6G network technology will further push the boundaries of IoT applications towards the so called Internet of Everything (IoE), including not only devices but also also people, processes and data, leveraging the integration of AI and machine learning @6G_survey.
On the other hand, the emerging and consolidated solutions offered by cloud computing, have enabled to store and process huge amounts of information generated by billions of devices. Furthermore, the integration of edge computing has enabled data processing closer to the source, reducing bandwidth and improving response times.\ 

Another critical aspect of IoT regards security, which includes all strategies of protecting digital resources such as systems, networks, data and devices against attacks from malicious and unauthorized users that may cause threats, damage, or disruption.
However, IoT networks are based on low-power and lossy networks which are constrained by energy, processing power and memory, as mentioned earlier. This brings different security challenges that cannot be addressed by traditional security mechanisms for classical wireless networks because are unsuitable or too resource-demanding. Consequently, appropriate encryption schemes are leveraged for ensuring the security of the IoT environment.\
Moreover, IoT data may deal with sensitive or life critical data, such as in healthcare or industrial applications, and this makes it even more challenging to ensure compliance with ethical issues, security laws and policies @iot_privacy.\
On the othen hand, IoT architectures must meet important security requirements. These are defined by the well-known CIA triad, which stands for Confidentiality, Integrity, and Availability. In this context, confidentiality ensures that sensitive information is accessible only to authorized entities, preventing unauthorized access and data breaches. Integrity guarantees that the data remains accurate and unaltered during transmission and storage, protecting against tampering or corruption. Availability ensures that services and data are accessible when needed, minimizing downtime.\
In addition to these core principles, authentication and non-repudiation mechanisms are also crucial. Authentication verifies the identity of devices and users, ensuring that only legitimate entities can access the network. Non repudiation provides proof of the origin and integrity of data, preventing entities from denying their actions.\
Together, all these security measures form a comprehensive framework to safeguard IoT systems and protect the privacy and safety of users and organizations against various threats and vulnerabilities.

== Problem statement <sec:problem_statement>
As we have seen from the previous sections, IoT faces significant and special challenges inherent of its characteristics.
This includes a massive number of connected devices, heterogeneity of the
exchanged data, scalability, mobility, and resources limitation and special security and privacy requirementsmaking it more complex than other networks.
[...]
\ \
Come discusso prima, la varietà di protocolli diversi richiede una gestione specifica per il tipo di dispositivo. Una architettura che possa gestire dispositivi eterogenei a valle di un'unica interfaccia di comunicazione è quindi auspicabile per semplificare la gestione della rete IoT.
Inoltre, gli aspetti di sicurezza sono fondamentali in un contesto IoT, dove dispositivi con risorse limitate possono essere vulnerabili ad attacchi informatici. La protezione dei dati trasmessi e la garanzia dell'integrità delle comunicazioni sono essenziali per mantenere la fiducia degli utenti e la sicurezza dell'intero sistema.


== Goals <sec:goals>


== Structure of the thesis <sec:structure_of_the_thesis>
