// All reusable variables here
#let myLang = "en"
#let myName = "Davide Spada"
#let myID = "2113495"
#let myTitle = "A Secure Multi-Protocol IoT Framework:"
#let myTitle2 = "Design, Implementation and Cyber Threat Analysis in Smart Agriculture Applications"
#let myDegree = "Master Thesis in Computer Science"
#let myUni = "University of Padova"
#let myDepartment = "Department of Mathematics ''Tullio Levi-Civita''"
#let myFaculty = "Master Degree in Computer Science"
#let profTitle = "Prof. "
#let myProf = "Alessandro Brighente"
#let supervisor = "Sandro Lain"
#let myCompany = "M31 S.r.l."
#let myTutor = "Nome Cognome"
#let myLocation = "Padova"
#let myAA = "2025-2026"
#let myTime = "April 2026"